global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: 7748871713:AAHcjT3WCn7vZ3MpW83GG9WltdURzmRYVHg
        chat_id: 6535471391

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
