version: '3.8'
services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    ports:
      - 19999:19999
    volumes:
      - netdata-config:/etc/netdata
      - netdata-cloud:/var/lib/netdata
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    restart: always

volumes:
  netdata-config:
  netdata-cloud:
